export const RateQuotePage = {
  NewQuoteButton:
    "//a[@class='mat-focus-indicator mat-flat-button mat-button-base mat-primary ng-star-inserted']//span[@class='mat-button-wrapper'][normalize-space()='New Quote']",
  Notnow:
    "//*[@id='mat-dialog-0']/ltlc-storage-notification-modal/mat-dialog-actions/button/span[1]",
  RoleDropdown: "//*[@id='mat-select-0']/div/div[2]",
  Role: "//*[@id='mat-option-28']/span",
  RoleConsignee: "//*[@id='mat-option-29']/span",
  RoleBillTo: "//*[@id='mat-option-30']/span",
  Frame: "//iframe[@src='https://id-sandbox.xpo.com/connect/checksession'",
  PickupDropdown: "//*[@data-placeholder='Search address, name, account id, etc.']",
  Pickup: "//*[@id='associated_111167768']/div[3]/div/div",
  PickupCA: "//mark[contains(text(),'A Plus Products Canada')]",
  PickupConsigneeDropdown: "//*[@id='mat-select-8']/div/div[2]/div",
  PickupConsigneeUS: "//*[@id='mat-option-32']/span/div",
  PickupConsigneeCA: "//*[@id='mat-option-33']/span/div",
  PickupConsigneeMX: "//*[@id='mat-option-34']/span/div",
  DeliveryConsigneeDropdown: "//*[@id='mat-input-7']",
  DeliveryConsigneeUS: "//*[@id='associated_615352285']/div[3]/div/div/span/b/span",
  DeliveryDropdown: "//*[@id='mat-select-6']/div/div[2]/div",
  DeliveryUS: "//*[@id='mat-option-1']/span/div",
  DeliveryCanada: "//*[@id='mat-option-2']/span/div",
  DeliveryMaxico: "//*[@id='mat-option-3']/span/div",
  PostalCode: "//*[@id='mat-input-5']",
  PostalCodeConsignee: "//*[@id='mat-input-8']",
  PaymentDropdown: "//*[@id='mat-select-2']/div/div[2]/div",
  Payment: "//*[@id='mat-option-4']/span",
  PaymentCollect: "//*[@id='mat-option-5']/span",
  FlatRateShipping: "//*[@id='mat-radio-2']/label/span[1]/span[2]",
  NumberOfPalletsDropdown: "//*[@id='mat-select-value-13']/span",
  ConsigneeNumberOfPalletsDropdown: "//*[@id='mat-select-value-15']/span",
  ConsigneeNumberOfPalletsDropdownMX: "//*[@id='mat-select-value-17']/span",
  NumberOfPallets: "//*[@id='mat-option-109']/span",
  NumberOdPalletsCA: "//*[@id='mat-option-71']/span",
  ConsigneeNumberOfPallets: "//*[@id='mat-option-113']/span",
  ConsigneeNumberOfPalletsMX: "//*[@id='mat-option-194']/span",
  CommodityDropdown: "//input[@data-placeholder='Type or Select']",
  Commodity: "//span[contains(text(),' BB23k ')]",
  MaxicoCityDropdown: "//*[@id='mat-select-value-13']/span",
  MaxicoCityName: "//*[@id='mat-option-115']/span",
  ConsigneeMaxicoCityDropdown: "//*[@id='mat-select-value-11']/span",
  ConsigneeMaxicoCity: "//*[@id='mat-option-60']/span",
  BillPickupLocationDropdown: "//*[@id='mat-select-10']/div/div[2]/div",
  BillPickupLocation: "//*[@id='mat-option-32']/span/div",
  BillPickupLocationCA: "//*[@id='mat-option-33']/span/div",
  BillPickupLocationMX: "//*[@id='mat-option-34']/span/div",
  BillPickupPostal: "//*[@id='mat-input-8']",
  BillDeliveryLocationDropdown: "//*[@id='mat-select-6']/div/div[2]",
  BillDeliveryLocationUS: "//*[@id='mat-option-1']/span/div",
  BillDeliveryLocationCA: "//*[@id='mat-option-2']/span/div",
  BillDeliveryLocationMX: "//*[@id='mat-option-3']/span/div",
  BillDeliveryPostalCode: "//*[@id='mat-input-5']",
  BillToFieldDropdown: "//*[@id='mat-input-7']",
  BillToField: "//*[@id='associated_29766522']/div[2]/div/div/span/b/span",
  BillNumberOfPalletsDropdown: "//*[@id='mat-select-value-17']/span",
  BillNumberOfPalletsMXDropdown: "//*[@id='mat-select-value-21']/span",
  BillPalletsUStoMXDropdown: "//*[@id='mat-select-value-19']/span",
  BillPalletsUStoMX: "//*[@id='mat-option-198']/span",
  BillNumberOfPalletsMX: "//*[@id='mat-option-278']/span",
  BillNumberOfPallets: "//*[@id='mat-option-116']/span",
  BillPaymentDropdown: "//*[@id='mat-select-value-9']",
  BillPaymentPrepaid: "//*[@id='mat-option-36']/span",
  BillPickupMexicoCityNameDropdown: "//*[@id='mat-select-value-13']/span",
  BillPickupMexicoCityName: "//*[@id='mat-option-63']/span",
  BillDeliveryMexicoCityNameDropdown: "//*[@id='mat-select-value-15']/span",
  BillDelUStoMXCityNameDropdown: "//*[@id='mat-select-value-13']/span",
  BillDelUStoMXCityName: "//*[@id='mat-option-61']/span",
  BillDeliveryMexicoCityName: "//*[@id='mat-option-142']/span",
  RateQuotebutton: '//mat-card-actions/button[1]/span[1]/div',
  NewRateQuote: '//ltlc-breadcrumbs/div/span',
  USD: "//mat-hint[text()='USD']",
  SaveAs: "//div[text()=' Save As New ']/parent::span/parent::button",
  Requote: "//span[text()=' requote ']",
};
