export const tokenBody = {
  grant_type: 'client_credentials',
};
export const createLocationBody = {
  location: {
    sicCd: 'CIP',
    sltTermAbbreviationName: 'TESTLOC',
    effectiveDate: '2023-10-15',
    locationTypeCd: 'OPERATIONS',
  },
  corporation: {
    corpCd: '7200',
  },
  satelliteType: 'CUSTOMER',
  parentSicCd: null,
  locationExtended: {
    financialSicInd: false,
    erpCompanyCd: '751',
    erpProfitCenterCd: 'CIL',
    erpDepartmentCd: '0003',
  },
};
export const ListPhoneBody = {
  address: {
    sicCd: 'CWU',
    addressId: '3036524896542',
    addressEffectiveDate: '2025-02-17',
    addressTypeCd: 'PHYSICAL',
    address1: '9151 BOULEVARD',
    address2: 'SUITE 100',
    address3: null,
    cityName: 'N RICHLAND HILLS',
    countryCd: 'US',
    countryName: 'UNITED STATES OF AMERICA',
    countrySubdivisionCd: 'TX',
    countrySubdivisionName: 'TEXAS',
    companyName: 'XPO LOGISTICS FREIGHT, INC.',
    deliveryInstructionDescription: '',
    expirationDate: '2025-02-17',
    primaryAddressInd: false,
    postalCd: '76180',
    postalCdExt: '5600',
    expiredReasonCd: 'MOVED_TO_NEW_ADDRESS',
    correlationId: null,
    listActionCd: 'Expire',
    auditInfo: null,
  },
  latitudeNbr: '45.357726',
  primaryAddressOverrideInd: false,
  longitudeNbr: '73.294556',
};
export const UpdatePhoneBody = {
  phone: {
    sicCd: 'UWR',
    phoneSequenceNbr: null,
    phoneAreaCd: 'KP',
    phoneNbr: '104097',
    phoneTypeCd: 'INTERNAL',
    primaryPhoneInd: false,
    listActionCd: 'Add',
  },
  primaryPhoneOverrideInd: false,
};
export const DeletePhoneBody = {
  address: {
    sicCd: 'CWY',
    addressId: '3036524896542',
    addressEffectiveDate: '2025-02-17',
    addressTypeCd: 'PHYSICAL',
    address1: '9151 BOULEVARD',
    address2: 'SUITE 100',
    address3: null,
    cityName: 'N RICHLAND HILLS',
    countryCd: 'US',
    countryName: 'UNITED STATES OF AMERICA',
    countrySubdivisionCd: 'TX',
    countrySubdivisionName: 'TEXAS',
    companyName: 'XPO LOGISTICS FREIGHT, INC.',
    deliveryInstructionDescription: '',
    expirationDate: '2025-02-17',
    primaryAddressInd: false,
    postalCd: '76180',
    postalCdExt: '5600',
    expiredReasonCd: 'MOVED_TO_NEW_ADDRESS',
    correlationId: null,
    listActionCd: 'Expire',
    auditInfo: null,
  },
  latitudeNbr: '45.357726',
  primaryAddressOverrideInd: false,
  longitudeNbr: '73.294556',
};
export const ListNoteBody = {
  address: {
    sicCd: 'CWY',
    addressId: '3036524896542',
    addressEffectiveDate: '2025-02-17',
    addressTypeCd: 'PHYSICAL',
    address1: '9151 BOULEVARD',
    address2: 'SUITE 100',
    address3: null,
    cityName: 'N RICHLAND HILLS',
    countryCd: 'US',
    countryName: 'UNITED STATES OF AMERICA',
    countrySubdivisionCd: 'TX',
    countrySubdivisionName: 'TEXAS',
    companyName: 'XPO LOGISTICS FREIGHT, INC.',
    deliveryInstructionDescription: '',
    expirationDate: '2025-02-17',
    primaryAddressInd: false,
    postalCd: '76180',
    postalCdExt: '5600',
    expiredReasonCd: 'MOVED_TO_NEW_ADDRESS',
    correlationId: null,
    listActionCd: 'Expire',
    auditInfo: null,
  },
  latitudeNbr: '45.357726',
  primaryAddressOverrideInd: false,
  longitudeNbr: '73.294556',
};
